package: bootstrapper
version: 1.0.0
author: Andreas Lenhardt
supportpage: https://github.com/AndiLeni/bootstrapper

page:
  title: Bootstrapper
  icon: rex-icon fa-cog
  subpages:
    install:
      title: Installation
    upload:
      title: Installation aus Datei
    installer:
      title: Installer
    export:
      title: Export

requires:
  redaxo: '^5.11'
  php:
    version: "^8.0"



installer_ignore:
    - .git
    - preview
