package: bootstrapper
version: dev-0.0.1
author: Andreas Lenhardt
supportpage: https://github.com/AndiLeni/bootstrapper

page:
  title: Bootstrapper
  icon: rex-icon fa-cog
  subpages:
    install:
      title: Installation
    installer:
      title: Installer

requires:
  redaxo: '^5.11'
  php:
    version: '>=7.1'



installer_ignore:
    - .git
    - preview
